version: '3'

volumes:
  db-store:

services:
  php:
    container_name: php
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./server:/work:delegated

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./server:/work:delegated
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - db-store:/var/lib/mysql:delegated    
    # - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf:delegated
    # - ./docker/db/sql:/docker-entrypoint-initdb.d:delegated
    ports:
    - 3306:3306